### PR TITLE
Add maxlength option and  truncate functionality

### PR DESCRIPTION
**Pull request by frcd**
Hi !
I was using npm package columnify which is old and have depreciated dependencies.
This package was just missing this truncate functionality for me.

### CODE REVIEW

**Comment by takamin** [comment]
Thanks for your Pull request.
I think it's nice feature, but the indents or quotes which do not relate the essentially feature are changed and tests are lacked.
Could you change the codes again for only the feature and add tests for the feature?

**Comment by takamin** [comment]
I am thinking that the maxlength option have to affect to the text cells only.
The number data should not be truncated.

**Comment by frcd** [comment]
i am using it to get a quick and easy to read representation of scraped data.
There can be a lot of columns, so in a case like mine, some could prefer clarity and ease of reading to exactitude. But yes, i'm thinking we could even do another sub option like truncateNumbers.

I'm very busy right now, so i might not be able to implement the required tests for list-it.
But i definitely want to use it in my project, instead of columnify, sooner or later.

**Comment by takamin** [comment]
Hi @dav-stern , I added a similar feature and merged the pull request #27 .
It is `ListIt#setColumnWidth(indexOfColumn:number, width:number)`.
I hope you like this feature.

I'm sorry that the interface is a little different from your previous implementation.

I will publish this changes as new version of the npm package and close this PullRequest later.

**Pull request closed without merging**
